"""Animation tuning values kept in one place."""

ANIMATIONS_ENABLED = True
FRAME_DELAY = 16
BOOT_DURATION = 1900
SCREEN_TRANSITION_DURATION = 420
SESSION_TRANSITION_DURATION = 1150
PANEL_ENTRANCE_DURATION = 640
MODAL_ENTRANCE_DURATION = 260
BUTTON_FEEDBACK_DURATION = 120
STAGGER_STEP = 70
DASHBOARD_ENTER_DURATION = 1200
DASHBOARD_EXIT_DURATION = 900
DASHBOARD_STAGGER = 100
APP_EXIT_DURATION = 280
